
/*       Proyecto         */


CREATE TABLE PERSONAS(

ID_PERSONA NUMBER(38) PRIMARY KEY,
NOMBRE VARCHAR2(30) CONSTRAINT PER_NOMB_NN NOT NULL,
APELLIDO1 VARCHAR2(30) CONSTRAINT PER_APE1_NN NOT NULL,
APELLIDO2 VARCHAR2(30) CONSTRAINT PER_APE2_NN NOT NULL);


CREATE TABLE TUTORES(
ID_PERSONA_TUTOR NUMBER(38) PRIMARY KEY, ---REVISAR
DNI VARCHAR2(10) CONSTRAINT TUT_DNI_NN NOT NULL,
TELEFONO1 NUMBER (9) CONSTRAINT TUT_TELF_NN NOT NULL,
TELEFONO2 NUMBER (9),
TELEFONO3 NUMBER (9),
TELEFONO4 NUMBER (9),

CONSTRAINT ID_PERSONA_TUTOR_FK FOREIGN KEY (ID_PERSONA_TUTOR) REFERENCES PERSONAS (ID_PERSONA)
);


CREATE TABLE MENORES(
ID_PERSONA_MENOR NUMBER(38)  PRIMARY KEY, ---REVISAR
CENTRO_ESTUDIO VARCHAR2(100) CONSTRAINT MEN_CENTROESTUDIO_NN NOT NULL,
MODELO VARCHAR2(1) CONSTRAINT MEN_MODELO_NN NOT NULL,
FECHA_NACHIMIENTO DATE CONSTRAINT MEN_FECHA_NN NOT NULL,
DISCAPACIDAD VARCHAR2(5),
DNI VARCHAR2(10),
SEXO VARCHAR2(1) CONSTRAINT MEN_SEXO_NN NOT NULL,
CODIGO_POSTAL NUMBER(5) CONSTRAINT MEN_CODPOSTAL_NN NOT NULL,
CALLE VARCHAR2(20) CONSTRAINT MEN_CALLE_NN NOT NULL,
NUMERO VARCHAR (4) CONSTRAINT MEN_NUMERO_NN NOT NULL,
PISO NUMBER(2) CONSTRAINT MEN_PISO_NN NOT NULL,
LETRA VARCHAR(10) CONSTRAINT MEN_LETRA_NN NOT NULL,
MUNICIPIO VARCHAR(30) CONSTRAINT MEN_MUNICIPIO_NN NOT NULL,
PROVINCIA VARCHAR(30) CONSTRAINT MEN_PROVINCIA_NN NOT NULL,

CONSTRAINT ID_PERSONA_MENOR_FK FOREIGN KEY(ID_PERSONA_MENOR) REFERENCES PERSONAS(ID_PERSONA)
);


CREATE TABLE SORTEO(
ANYO NUMBER(4) PRIMARY KEY,
NUM_INICIAL NUMBER(38),
CADENCIA NUMBER(1),
FECHA_COMIENZO_INSCRIPCION DATE
);


CREATE TABLE SOLICITUD(
ID_SOLICITUD NUMBER(38) PRIMARY KEY,
FECHA_SOLICITUD DATE DEFAULT SYSDATE,
NUM_ORDEN NUMBER (38),
FECHA_CITA DATE,
HORA_CITA DATE,
ANYO NUMBER(4)
);

-------------------------------------fALTAN DE METER

CREATE TABLE PARTICIPACION(
ID_PERSONA_TUTOR NUMBER(38) PRIMARY KEY, ---REVISAR
ID_PERSONA_MENOR NUMBER(38) PRIMARY KEY, ---REVISAR
ID_SOLICITUD NUMBER (38),

CONSTRAINT ID_PERSONA_TUTOR_FK FOREIGN KEY(ID_PERSONA_TUTOR) REFERENCES PERSONAS(ID_PERSONA),
CONSTRAINT ID_PERSONA_MENOR_FK FOREIGN KEY (ID_PERSONA_MENOR) REFERENCES PERSONAS(ID_PERSONA),
CONSTRAINT ID_SOLICITUD_FK FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD(ID_SOLICITUD),
);









